IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'ChiQuadrat')
BEGIN
create database ChiQuadrat
END
GO

USE ChiQuadrat;
GO
/****** Object:  Table [dbo].[CHI_SQUARE]    Script Date: 22.08.2025 10:38:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHI_SQUARE](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[BEHANDLUNG] [nvarchar](255) NULL,
	[RESULTAT] [nvarchar](255) NULL,
	[SEX] [char](1) NULL,
 CONSTRAINT [PK_CHI_SQUARE] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[CHI_SQUARE] ON 

INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1087, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1088, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1089, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1090, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1091, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1092, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1093, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1094, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1095, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1096, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1097, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1098, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1099, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1100, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1101, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1102, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1103, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1104, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1105, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1106, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1107, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1108, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1109, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1110, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1111, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1112, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1113, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1114, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1115, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1116, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1117, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1118, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1119, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1120, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1121, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1122, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1123, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1124, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1125, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1126, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1127, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1128, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1129, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1130, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1131, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1132, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1133, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1134, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1135, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1136, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1137, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1138, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1139, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1140, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1141, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1142, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1143, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1144, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1145, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1146, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1147, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1148, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1149, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1150, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1151, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1152, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1153, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1154, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1155, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1156, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1157, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1158, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1159, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1160, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1161, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1162, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1163, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1164, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1165, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1166, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1167, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1168, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1169, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1170, N'üblich', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1171, N'üblich', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1172, N'üblich', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1173, N'üblich', N'gestorben', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1174, N'üblich', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1175, N'üblich', N'gestorben', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1176, N'üblich', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1177, N'üblich', N'gestorben', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1178, N'üblich', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1179, N'üblich', N'gestorben', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1180, N'üblich', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1181, N'üblich', N'gestorben', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1182, N'üblich', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1183, N'üblich', N'gestorben', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1184, N'üblich', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1185, N'üblich', N'gestorben', N'w')
GO
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1186, N'üblich', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1187, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1188, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1189, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1190, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1191, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1192, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1193, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1194, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1195, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1196, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1197, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1198, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1199, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1200, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1201, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1202, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1203, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1204, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1205, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1206, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1207, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1208, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1209, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1210, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1211, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1212, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1213, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1214, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1215, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1216, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1217, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1218, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1219, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1220, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1221, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1222, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1223, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1224, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1225, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1226, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1227, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1228, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1229, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1230, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1231, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1232, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1233, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1234, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1235, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1236, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1237, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1238, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1239, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1240, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1241, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1242, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1243, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1244, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1245, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1246, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1247, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1248, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1249, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1250, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1251, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1252, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1253, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1254, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1255, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1256, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1257, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1258, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1259, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1260, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1261, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1262, N'neu', N'geheilt', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1263, N'neu', N'geheilt', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1264, N'neu', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1265, N'neu', N'gestorben', N'w')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1266, N'neu', N'gestorben', N'm')
INSERT [dbo].[CHI_SQUARE] ([id], [BEHANDLUNG], [RESULTAT], [SEX]) VALUES (1267, N'neu', N'gestorben', N'w')
SET IDENTITY_INSERT [dbo].[CHI_SQUARE] OFF
GO
EXEC sys.sp_addextendedproperty @name=N'TREE', @value=N'PK' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CHI_SQUARE', @level2type=N'COLUMN',@level2name=N'id'
GO
EXEC sys.sp_addextendedproperty @name=N'TREE', @value=N'INDEPENDENT_VARIABLE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CHI_SQUARE', @level2type=N'COLUMN',@level2name=N'BEHANDLUNG'
GO
EXEC sys.sp_addextendedproperty @name=N'TREE', @value=N'DEPENDENT_VARIABLE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CHI_SQUARE', @level2type=N'COLUMN',@level2name=N'RESULTAT'
GO
EXEC sys.sp_addextendedproperty @name=N'TREE', @value=N'INDEPENDENT_VARIABLE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CHI_SQUARE', @level2type=N'COLUMN',@level2name=N'SEX'
GO
